apiVersion: v1
kind: ConfigMap
metadata:
  name: apar-frontend-configmap
  namespace: apar
data:
  VUE_APP_GRAPHQL_URL: "https://api.apar.live/graphql/"
  VUE_APP_DJANGO_URL: "https://api.apar.live/"
  NODE_ENV: production
---
apiVersion: apps/v1
kind: Deployment
metadata:  
  name: apar-frontend-deployment
  namespace: apar
  labels:    
    app: apar-frontend
spec:  
  replicas: 1  
  selector:    
    matchLabels:
      app: apar-frontend
  template:
    metadata:
      labels:
        app: apar-frontend
    spec: 
      containers:
      - name: apar-frontend
        image: simojoe/apar-frontend:latest
        envFrom:
        - configMapRef:
            name: apar-frontend-configmap
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
  name: apar-frontend-service
  namespace: apar
  labels:
    app: apar-frontend
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
    nodePort: 32121
  selector:
    app: apar-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apar-frontend-ingress
  namespace: apar
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - host: apar.live
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: apar-frontend-service
              port: 
                number: 8000