apiVersion: apps/v1
kind: Deployment
metadata:  
  name: apar-frontend-deployment
  namespace: apar
  labels:    
    app: apar-frontend
spec:  
  replicas: 1  
  selector:    
    matchLabels:
      app: apar-frontend
  template:
    metadata:
      labels:
        app: apar-frontend
    spec: 
     containers:
      - name: apar-frontend
        image: simojoe/apar-frontend
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
  name: apar-frontend-service
  namespace: apar
  labels:
    app: apar-frontend
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
    nodePort: 32121
  selector:
    app: apar-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apar-frontend-ingress
  namespace: apar
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: apar.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: apar-frontend-service
              port: 
                number: 8000